// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtoSCADA.Data.Context;

#nullable disable

namespace ProtoSCADA.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241230122026_UpdateRelationshipsAndSchema")]
    partial class UpdateRelationshipsAndSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Alert", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte>("Condition")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FactoryID")
                        .HasColumnType("int");

                    b.Property<int>("LineID")
                        .HasColumnType("int");

                    b.Property<int>("MachineID")
                        .HasColumnType("int");

                    b.Property<float>("ThresholdValue")
                        .HasColumnType("real");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FactoryID")
                        .HasDatabaseName("IX_Alert_FactoryID");

                    b.HasIndex("LineID");

                    b.HasIndex("MachineID");

                    b.HasIndex("UserID");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FactoryID")
                        .HasColumnType("int");

                    b.Property<int>("LineID")
                        .HasColumnType("int");

                    b.Property<int>("MachineID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FactoryID")
                        .HasDatabaseName("IX_Event_FactoryID");

                    b.HasIndex("LineID");

                    b.HasIndex("MachineID");

                    b.HasIndex("UserID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Factory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Line", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FactoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FactoryID")
                        .HasDatabaseName("IX_Line_FactoryID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Machine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FactoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FactoryID")
                        .HasDatabaseName("IX_Machine_FactoryID");

                    b.HasIndex("LineID");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Metric", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("MachineID");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Report", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FactoryID")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("LineID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("FactoryID")
                        .HasDatabaseName("IX_Report_FactoryID");

                    b.HasIndex("LineID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FactoryID")
                        .HasColumnType("int");

                    b.Property<int>("LineID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FactoryID");

                    b.HasIndex("LineID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Alert", b =>
                {
                    b.HasOne("ProtoSCADA.Entities.Entities.Factory", "Factory")
                        .WithMany("Alerts")
                        .HasForeignKey("FactoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Line", "Line")
                        .WithMany("Alerts")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Machine", "Machine")
                        .WithMany("Alerts")
                        .HasForeignKey("MachineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.User", null)
                        .WithMany("Alerts")
                        .HasForeignKey("UserID");

                    b.Navigation("Factory");

                    b.Navigation("Line");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Event", b =>
                {
                    b.HasOne("ProtoSCADA.Entities.Entities.Factory", "Factory")
                        .WithMany("Events")
                        .HasForeignKey("FactoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Line", "Line")
                        .WithMany("Events")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Machine", "Machine")
                        .WithMany("Events")
                        .HasForeignKey("MachineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("Line");

                    b.Navigation("Machine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Line", b =>
                {
                    b.HasOne("ProtoSCADA.Entities.Entities.Factory", "Factory")
                        .WithMany("Lines")
                        .HasForeignKey("FactoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Machine", b =>
                {
                    b.HasOne("ProtoSCADA.Entities.Entities.Factory", "Factory")
                        .WithMany("Machines")
                        .HasForeignKey("FactoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Line", "Line")
                        .WithMany("Machines")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Metric", b =>
                {
                    b.HasOne("ProtoSCADA.Entities.Entities.Machine", "Machine")
                        .WithMany("Metrics")
                        .HasForeignKey("MachineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Report", b =>
                {
                    b.HasOne("ProtoSCADA.Entities.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Factory", "Factory")
                        .WithMany("Reports")
                        .HasForeignKey("FactoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Line", "Line")
                        .WithMany("Reports")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Factory");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.User", b =>
                {
                    b.HasOne("ProtoSCADA.Entities.Entities.Factory", "Factory")
                        .WithMany("Users")
                        .HasForeignKey("FactoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtoSCADA.Entities.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("Line");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Factory", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Events");

                    b.Navigation("Lines");

                    b.Navigation("Machines");

                    b.Navigation("Reports");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Line", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Events");

                    b.Navigation("Machines");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.Machine", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Events");

                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("ProtoSCADA.Entities.Entities.User", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
